### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by sliu2013** [wavefrontHQ/wavefront-opentracing-sdk-python#2]
* Need to specify the required tags ("application", "service"). These 2 tags are required in order for users to use span-search qb in Wavefront
* If we can include the instruction about span extract/inject in the README, that will be great. Or the other way is to provide a URL link to the opentracing-sdk doc?!

**Comment by song-hao** [comment]
@sliu2013 PR https://github.com/wavefrontHQ/wavefront-opentracing-sdk-python/pull/3 : `Application` and `Service` are added via `ApplicationTags` similar to Java Opentracing SDK.
@susanjlindner We should consider adding the similar page of [Context Propagation](https://github.com/wavefrontHQ/wavefront-opentracing-sdk-java/blob/master/docs/contextpropagation.md) for Python.
