### ISSUE TITLE
Reporter does not work in forked process

### ISSUE THREAD

**Issue by AgDude** [wavefrontHQ/wavefront-opentracing-sdk-python#34]
I am trying to instrument an application which runs in celery. The SpanReporter is initialized, then the process forks. There is currently no way to recreate the `sending_thread` in the new process created by the fork.

Other wavefront reporters rely on pyformance to handle this, but this reporter does not inherit from pyformance.

**Comment by sushantdewan123** [comment]
Won't fix this issue for now.
